#!/bin/sh
# debian/config script for the package
# Copyright 2010-2011 by Gerfried Fuchs <rhonda@debian.org>
# Licenced under WTFPLv2

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# ask for user to create
db_input high easy-backup/backupuser || true
db_go

# ask for a public key
db_input high easy-backup/public_key || true
db_go

exit 0
